# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - '*'
    exclude:
    - features/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'git-values'

steps:
- task: CmdLine@2
  displayName: Git Pull
  inputs:
    script: 'git pull https://$(pat)@github.com/JacobBN/portfolio.git $(Build.SourceBranchName)'
- task: Npm@1
  displayName: Install Dependencies
  inputs:
    command: 'install'
- task: CmdLine@2
  displayName: Run Unit Tests
  inputs:
    script: 'CI=true npm run test:unit'
- task: CmdLine@2
  displayName: Git Push
  inputs:
    script: 'git push https://$(pat)@github.com/JacobBN/portfolio.git HEAD:$(Build.SourceBranchName)'
